export { default as Home } from './Home/Home.jsx'
export { default as NewSpotForm } from './NewSpotForm/NewSpotForm.jsx'
export { default as ManageSpots } from './ManageSpots/ManageSpots.jsx'
export { default as UpdateSpot } from './UpdateSpot/UpdateSpot.jsx'
export { default as ManageReviews } from './ManageReviews/ManageReviews.jsx'
